"""tenants, users, login sessions, billing events

Bechne ka commercial layer: kaun sa shop, kaun sa plan, kaun login kar
sakta hai, aur paisa kab aaya. Business tables ko haath nahi lagta.

Revision ID: 6e9d756eaef0
Revises: e5b2c8f1a37d
Create Date: 2026-08-06 10:24:47.440819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6e9d756eaef0'
down_revision: Union[str, Sequence[str], None] = 'e5b2c8f1a37d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=40), nullable=False),
    sa.Column('shop_name', sa.String(length=120), nullable=False),
    sa.Column('owner_name', sa.String(length=120), nullable=False),
    sa.Column('owner_phone', sa.String(length=20), nullable=False),
    sa.Column('owner_email', sa.String(length=160), nullable=True),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('plan', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='trial', nullable=False),
    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('setup_fee_paid', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('rzp_customer_id', sa.String(length=60), nullable=True),
    sa.Column('rzp_subscription_id', sa.String(length=60), nullable=True),
    sa.Column('onboarding_done', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenants'))
    )
    op.create_index(op.f('ix_tenants_owner_phone'), 'tenants', ['owner_phone'], unique=False)
    op.create_index(op.f('ix_tenants_rzp_subscription_id'), 'tenants', ['rzp_subscription_id'], unique=False)
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_index(op.f('ix_tenants_status'), 'tenants', ['status'], unique=False)
    op.create_table('billing_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('event_id', sa.String(length=80), nullable=False),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('amount_paise', sa.Integer(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_billing_events_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_billing_events'))
    )
    op.create_index(op.f('ix_billing_events_at'), 'billing_events', ['at'], unique=False)
    op.create_index(op.f('ix_billing_events_event_id'), 'billing_events', ['event_id'], unique=True)
    op.create_index(op.f('ix_billing_events_event_type'), 'billing_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_billing_events_tenant_id'), 'billing_events', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('must_change_password', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_users_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_users_tenant_email')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_index('ix_users_tenant_role', 'users', ['tenant_id', 'role'], unique=False)
    op.create_table('login_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_login_sessions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_login_sessions'))
    )
    op.create_index(op.f('ix_login_sessions_expires_at'), 'login_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_login_sessions_token_hash'), 'login_sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_login_sessions_user_id'), 'login_sessions', ['user_id'], unique=False)
    # NOTE: autogenerate ne kuch purane index rename karne ko kaha tha —
    # wo is migration ka kaam nahi (naye tables se koi lena-dena nahi).
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_login_sessions_user_id'), table_name='login_sessions')
    op.drop_index(op.f('ix_login_sessions_token_hash'), table_name='login_sessions')
    op.drop_index(op.f('ix_login_sessions_expires_at'), table_name='login_sessions')
    op.drop_table('login_sessions')
    op.drop_index('ix_users_tenant_role', table_name='users')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_billing_events_tenant_id'), table_name='billing_events')
    op.drop_index(op.f('ix_billing_events_event_type'), table_name='billing_events')
    op.drop_index(op.f('ix_billing_events_event_id'), table_name='billing_events')
    op.drop_index(op.f('ix_billing_events_at'), table_name='billing_events')
    op.drop_table('billing_events')
    op.drop_index(op.f('ix_tenants_status'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_rzp_subscription_id'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_owner_phone'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
