"""rate card table

Revision ID: 8e9cd8eda965
Revises: 98ca7c56a958
Create Date: 2026-08-02 23:34:04.919176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e9cd8eda965'
down_revision: Union[str, Sequence[str], None] = '98ca7c56a958'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_card',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('service', sa.String(length=60), nullable=False),
    sa.Column('garment', sa.String(length=60), nullable=False),
    sa.Column('unit', sa.String(length=2), nullable=False),
    sa.Column('rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rate_card')),
    sa.UniqueConstraint('service', 'garment', name='uq_service_garment')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rate_card')
    # ### end Alembic commands ###
