"""add sent_by to conversations

Revision ID: ad989620b1d0
Revises: 8a096781253c
Create Date: 2026-08-02 22:12:09.123055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad989620b1d0'
down_revision: Union[str, Sequence[str], None] = '8a096781253c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('sent_by', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'sent_by')
    # ### end Alembic commands ###
