"""leads table

Revision ID: ba1f7299158e
Revises: 1070167d3a06
Create Date: 2026-08-03 23:57:23.817405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba1f7299158e'
down_revision: Union[str, Sequence[str], None] = '1070167d3a06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('area', sa.String(length=120), nullable=True),
    sa.Column('items_text', sa.String(length=300), nullable=True),
    sa.Column('stage', sa.String(length=12), server_default='NEW', nullable=False),
    sa.Column('followup_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_contact_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_followup_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leads'))
    )
    op.create_index(op.f('ix_leads_next_followup_at'), 'leads', ['next_followup_at'], unique=False)
    op.create_index(op.f('ix_leads_phone'), 'leads', ['phone'], unique=True)
    op.create_index(op.f('ix_leads_stage'), 'leads', ['stage'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leads_stage'), table_name='leads')
    op.drop_index(op.f('ix_leads_phone'), table_name='leads')
    op.drop_index(op.f('ix_leads_next_followup_at'), table_name='leads')
    op.drop_table('leads')
    # ### end Alembic commands ###
