"""phase agent+marketing: ledger, audit, campaigns, coupons, knowledge

Revision ID: c35f62d3ae42
Revises: 8e9cd8eda965
Create Date: 2026-08-03 02:27:07.025959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c35f62d3ae42'
down_revision: Union[str, Sequence[str], None] = '8e9cd8eda965'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor_role', sa.String(length=20), nullable=False),
    sa.Column('actor', sa.String(length=80), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('args', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('ok', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_at'), 'audit_log', ['at'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('segment', sa.String(length=40), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('template_name', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=12), server_default='draft', nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('coupon_code', sa.String(length=30), nullable=True),
    sa.Column('created_by', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaigns'))
    )
    op.create_index(op.f('ix_campaigns_status'), 'campaigns', ['status'], unique=False)
    op.create_table('corrections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('correct_reply', sa.Text(), nullable=False),
    sa.Column('audience', sa.String(length=12), server_default='customer', nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_corrections'))
    )
    op.create_table('faq_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('audience', sa.String(length=12), server_default='customer', nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_faq_entries'))
    )
    op.create_table('sent_events',
    sa.Column('event_key', sa.String(length=120), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('event_key', name=op.f('pk_sent_events'))
    )
    op.create_table('settings_kv',
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_settings_kv'))
    )
    op.create_table('campaign_recipients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=12), server_default='queued', nullable=False),
    sa.Column('wa_message_id', sa.String(length=120), nullable=True),
    sa.Column('detail', sa.String(length=200), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_campaign_recipients_campaign_id_campaigns')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_campaign_recipients_customer_id_customers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaign_recipients')),
    sa.UniqueConstraint('campaign_id', 'customer_id', name='uq_campaign_customer')
    )
    op.create_index(op.f('ix_campaign_recipients_campaign_id'), 'campaign_recipients', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_recipients_customer_id'), 'campaign_recipients', ['customer_id'], unique=False)
    op.create_index(op.f('ix_campaign_recipients_wa_message_id'), 'campaign_recipients', ['wa_message_id'], unique=False)
    op.create_table('coupons',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('discount_type', sa.String(length=8), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('min_order', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('per_customer_limit', sa.Integer(), server_default='1', nullable=False),
    sa.Column('total_limit', sa.Integer(), nullable=True),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_coupons_campaign_id_campaigns')),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_coupons'))
    )
    op.create_table('coupon_redemptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('coupon_code', sa.String(length=30), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('discount_applied', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['coupon_code'], ['coupons.code'], name=op.f('fk_coupon_redemptions_coupon_code_coupons')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_coupon_redemptions_customer_id_customers')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_coupon_redemptions_order_id_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coupon_redemptions'))
    )
    op.create_index(op.f('ix_coupon_redemptions_coupon_code'), 'coupon_redemptions', ['coupon_code'], unique=False)
    op.create_index(op.f('ix_coupon_redemptions_customer_id'), 'coupon_redemptions', ['customer_id'], unique=False)
    op.create_table('open_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=12), server_default='open', nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('asked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_open_questions_customer_id_customers')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_open_questions_order_id_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_open_questions'))
    )
    op.create_index(op.f('ix_open_questions_customer_id'), 'open_questions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_open_questions_status'), 'open_questions', ['status'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    # create_type=False: the payment_method enum already exists (orders table)
    sa.Column('method', postgresql.ENUM('CASH', 'UPI', 'OTHER', name='payment_method', create_type=False), nullable=False),
    sa.Column('recorded_by', sa.String(length=80), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_payments_order_id_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments'))
    )
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=False)
    op.add_column('customers', sa.Column('marketing_opt_out', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('customers', sa.Column('last_marketing_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('customers', sa.Column('agent_paused', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('customers', sa.Column('birthday', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('priority', sa.String(length=10), server_default='normal', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'priority')
    op.drop_column('customers', 'birthday')
    op.drop_column('customers', 'agent_paused')
    op.drop_column('customers', 'last_marketing_at')
    op.drop_column('customers', 'marketing_opt_out')
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_open_questions_status'), table_name='open_questions')
    op.drop_index(op.f('ix_open_questions_customer_id'), table_name='open_questions')
    op.drop_table('open_questions')
    op.drop_index(op.f('ix_coupon_redemptions_customer_id'), table_name='coupon_redemptions')
    op.drop_index(op.f('ix_coupon_redemptions_coupon_code'), table_name='coupon_redemptions')
    op.drop_table('coupon_redemptions')
    op.drop_table('coupons')
    op.drop_index(op.f('ix_campaign_recipients_wa_message_id'), table_name='campaign_recipients')
    op.drop_index(op.f('ix_campaign_recipients_customer_id'), table_name='campaign_recipients')
    op.drop_index(op.f('ix_campaign_recipients_campaign_id'), table_name='campaign_recipients')
    op.drop_table('campaign_recipients')
    op.drop_table('settings_kv')
    op.drop_table('sent_events')
    op.drop_table('faq_entries')
    op.drop_table('corrections')
    op.drop_index(op.f('ix_campaigns_status'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_audit_log_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
