"""doc_chunks for uploaded training documents

Revision ID: e3954f7423ce
Revises: c35f62d3ae42
Create Date: 2026-08-03 08:17:14.413291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3954f7423ce'
down_revision: Union[str, Sequence[str], None] = 'c35f62d3ae42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doc_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document', sa.String(length=160), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_doc_chunks'))
    )
    op.create_index(op.f('ix_doc_chunks_document'), 'doc_chunks', ['document'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_doc_chunks_document'), table_name='doc_chunks')
    op.drop_table('doc_chunks')
    # ### end Alembic commands ###
